### PR TITLE
Added option to separate install prefix from image directory

### PR DESCRIPTION
**Pull request by gentryx**
Hi, this PR allows package maintainers to configure a different directory for placing files via "make installl" than the executables/libraries will expect at runtime. Most (Linux distribution) packaging tools expect both to be different.

### CODE REVIEW

**Comment by TomTheBear** [comment]
Hi,

thanks for your work. I already started implementing this, too.

I have a small question: Why didn't you change every occurrence of PREFIX? As far as I understand it, the PREFIX, BINPREFIX, ... are only used for building while INSTALLED_PREFIX,... are used during installation. In the likwid.lua file, you changed only one path to INSTALLED_PREFIX while two other lines with PREFIX are kept unchanged.

Greetings,
Thomas

**Comment by gentryx** [comment]
Oops, omitting those was an oversight. Fixed.

**Comment by TomTheBear** [comment]
Thanks for fixing the remaining path variables.

I know that chown'ing of files to root is not desirable but before I did that, I got uncountable emails that it does not work for their machine. The main reason was that they simply forgot to set the user of the access and the frequency daemon to root or set the suid bit before changing the user what deletes the suid bit again. Do you know a solution for this? It was not enough to document it.

**Comment by gentryx** [comment]
Got it. I added an option to config.mk so packagers can disable it, but for users chowning to root will stay on. Would that be acceptable for you?

**Comment by TomTheBear** [comment]
OK, thanks. That's fine for me. I merge the branches now.

**Comment by gentryx** [comment]
Cool, this is highly appreciated. Could you push out a 4.0.1 release? I'd then update the Gentoo ebuild. ATM all official Gentoo packages for likwid are broken and I'd be happy to get this fixed. :-)

**Comment by TomTheBear** [comment]
I planned to do it this week. I have to do some tests before I can release it.

**Pull request merged**
